version: "3.5"
services:
  centos7php7base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: aursu/php7build:7-base
  centos8php7base:
    build:
      context: .
      dockerfile: Dockerfile.8-base
    image: aursu/php7build:8-base
