version: "3.5"
services:
  centos7php7base:
    networks:
      - buildnet
    build:
      context: .
      dockerfile: Dockerfile.el7-base
      network: buildnet
    image: rpmbuild:7-php7base
  centos7php7:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
      dockerfile: Dockerfile.el7
    image: rpmbuild:7-php7build
  centos7php7rel:
    command: ["-ba", "--with", "relocation"]
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
      dockerfile: Dockerfile.el7
    image: rpmbuild:7-php7build
  centos7php7my:
    command: ["-ba", "--with", "libmysql"]
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
      dockerfile: Dockerfile.el7
    image: rpmbuild:7-php7build

volumes:
  rpms:
    name: rpms
  rpm7:
    name: rpm7

networks:
  buildnet:
    external: true
    name: buildnet
