version: 2.1

orbs:
  git:
    commands:
      submodules:
        description: Git submodules sync
        steps:
          - checkout
          - run:
              name: Git submodules sync and update
              command: |
                git submodule sync
                git submodule update --init
  docker-rpmbuild:
    commands:
      base:
        description: Create base image for rpmbuild
        parameters:
          file:
            type: string
            default: "docker-compose.base.yml"
          service:
            type: string
        steps:
          - run:
              name: Create base image using << parameters.service >>
              command: docker-compose -f << parameters.file >> build --no-cache --pull << parameters.service >>
      build:
        description: Create build image for rpmbuild
        parameters:
          file:
            type: string
            default: "docker-compose.yml"
          service:
            type: string
        steps:
          - run:
              name: Create build image using << parameters.service >>
              command: docker-compose -f << parameters.file >> build --no-cache << parameters.service >>
      rpm:
        description: Create rpm packages with rpmbuild
        parameters:
          file:
            type: string
            default: "docker-compose.yml"
          service:
            type: string
        steps:
          - run:
              name: Build RPM packages using << parameters.service >>
              command: docker-compose -f << parameters.file >> up << parameters.service >>
      bintray:
        description: Upload RPM packages into BinTray
        parameters:
          uploader:
            type: string
        steps:
          - run:
            name: Get Docker image for uploader << parameters.uploader >>
            command: docker-compose -f rpmbuild/docker-compose.bintray.yml pull << parameters.uploader >>
          - run:
              name: Upload RPM packages into BinTray using uploader << parameters.uploader >>
              command: |
                docker-compose -f rpmbuild/docker-compose.bintray.yml run --rm \
                  -e BINTRAY_USER=$BINTRAY_USER \
                  -e BINTRAY_API_KEY=$BINTRAY_API_KEY \
                  -e BINTRAY_REPO=$BINTRAY_REPO \
                  -e PACKAGE_VCS_URL=$PACKAGE_VCS_URL << parameters.uploader >>


jobs:
  centos7php7:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      BINTRAY_REPO: php71custom
      PACKAGE_VCS_URL: https://github.com/aursu/rpmbuild-php-7.1
    steps:
      - git/submodules
      - docker-rpmbuild/base:
          service: centos7php7base
      - docker-rpmbuild/build:
          service: centos7php7
      - docker-rpmbuild/rpm:
          service: centos7php7
      - docker-rpmbuild/bintray:
          uploader: centos7bintray
  centos7php7rel:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      BINTRAY_REPO: php71custom
      PACKAGE_VCS_URL: https://github.com/aursu/rpmbuild-php-7.1
    steps:
      - git/submodules
      - docker-rpmbuild/base:
          service: centos7php7base
      - docker-rpmbuild/build:
          service: centos7php7rel
      - docker-rpmbuild/rpm:
          service: centos7php7rel
      - docker-rpmbuild/bintray:
          uploader: centos7bintray
  build:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      BINTRAY_REPO: php71custom
      PACKAGE_VCS_URL: https://github.com/aursu/rpmbuild-php-7.1
    steps:
      - git/submodules
      - run:
          name: Build PHP Docker images (PHP 7.1)
          command: docker-compose -f build/docker-compose.yml build --no-cache --pull
      - run:
          name: Upload PHP Docker images (PHP 7.1)
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push aursu/php7build:7-build
            docker push aursu/php7build:7-build-rel
      - run:
          name: Build PHP Docker runtime images (PHP 7.1)
          command: |
            docker-compose -f run/docker-compose.yml build --no-cache --pull
            docker-compose -f run/docker-compose.dev.yml build --no-cache centos7php7dev
      - run:
          name: Upload PHP Docker runtime images (PHP 7.1)
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push aursu/php7build:7-runtime
            docker push aursu/php7build:7-dev
  build8:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      BINTRAY_REPO: php71custom
      PACKAGE_VCS_URL: https://github.com/aursu/rpmbuild-php-7.1
    steps:
      - checkout
      - run:
          name: Git submodules sync
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: Pull images for RPM build docker services
          command: |
            docker-compose -f rpmbuild/docker-compose.yml pull
            docker-compose -f rpmbuild/docker-compose.bintray.yml pull
            docker-compose -f rpmbuild/docker-compose.refresh.yml pull
      - run:
          name: Start docker services for rpmbuild
          command: docker-compose -f rpmbuild/docker-compose.yml up -d
          background: true
          no_output_timeout: 2h
      - run:
          name: Build PHP Docker images
          command: |
            docker-compose -f docker-compose.base.yml build --no-cache --pull centos8php7base
            docker-compose -f docker-compose.el8.yml build --no-cache
      - run:
          name: Build PHP 7.1 RPM packages
          command: docker-compose -f docker-compose.el8.yml up
      - run:
          name: Upload RPM packages into Bintray
          command: |
            docker-compose -f rpmbuild/docker-compose.bintray.yml run --rm \
              -e BINTRAY_USER=$BINTRAY_USER \
              -e BINTRAY_API_KEY=$BINTRAY_API_KEY \
              -e BINTRAY_REPO=$BINTRAY_REPO \
              -e PACKAGE_VCS_URL=$PACKAGE_VCS_URL centos8bintray
      - run:
          name: refresh repositories
          command: docker-compose -f rpmbuild/docker-compose.refresh.yml run --rm centos8refresh
      - run:
          name: Build PHP Docker images (PHP 7.1)
          command: docker-compose -f build/docker-compose.el8.yml build --no-cache --pull
      - run:
          name: Upload PHP Docker images (PHP 7.1)
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push aursu/php7build:8-build
            docker push aursu/php7build:8-build-rel
      - run:
          name: Build PHP Docker runtime images (PHP 7.1)
          command: |
            docker-compose -f run/docker-compose.el8.yml build --no-cache --pull
            docker-compose -f run/docker-compose.dev.yml build --no-cache centos8php7dev
      - run:
          name: Upload PHP Docker images (PHP 7.1)
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push aursu/php7build:8-runtime
            docker push aursu/php7build:8-dev

workflows:
  version: 2
  php7build:
    jobs:
      - centos7php7
      - centos7php7rel
      - build:
          requires:
            - centos7php7
            - centos7php7rel
      - build8