version: 2.1

orbs:
  docker-rpmbuild:
    executors:
      centos:
        machine:
          image: ubuntu-1604:201903-01
        environment:
          OS6: 6.10
          OS7: 7.7.1908
          OS8: 8.1.1911
          OS6TAG: 6.10
          OS7TAG: 7.7.1908
          OS8TAG: 8.1.1911
    commands:
      submodules:
        description: Git submodules sync
        steps:
          - checkout
          - run:
              name: Git submodules sync and update
              command: |
                git submodule sync
                git submodule update --init
      base:
        description: Create base image for rpmbuild
        parameters:
          file:
            type: string
            default: "docker-compose.base.yml"
          service:
            type: string
        steps:
          - run:
              name: Create base image using << parameters.service >>
              command: docker-compose -f << parameters.file >> build --no-cache --pull << parameters.service >>
      build:
        description: Create build image for rpmbuild
        parameters:
          file:
            type: string
            default: "docker-compose.yml"
          service:
            type: string
        steps:
          - run:
              name: Create build image using << parameters.service >>
              command: docker-compose -f << parameters.file >> build --no-cache << parameters.service >>
      rpm:
        description: Create rpm packages with rpmbuild
        parameters:
          file:
            type: string
            default: "docker-compose.yml"
          service:
            type: string
        steps:
          - run:
              name: Build RPM packages using << parameters.service >>
              command: docker-compose -f << parameters.file >> up << parameters.service >>
      bintray:
        description: Upload RPM packages into BinTray
        parameters:
          uploader:
            type: string
        steps:
          - run:
              name: Get Docker image for uploader << parameters.uploader >>
              command: docker-compose -f rpmbuild/docker-compose.bintray.yml pull << parameters.uploader >>
          - run:
              name: Upload RPM packages into BinTray using uploader << parameters.uploader >>
              command: |
                docker-compose -f rpmbuild/docker-compose.bintray.yml run --rm \
                  -e BINTRAY_USER=$BINTRAY_USER \
                  -e BINTRAY_API_KEY=$BINTRAY_API_KEY \
                  -e BINTRAY_REPO=$BINTRAY_REPO \
                  -e PACKAGE_VCS_URL=$PACKAGE_VCS_URL << parameters.uploader >>
      image:
        description: Build Docker image for App development
        parameters:
          file:
            type: string
          service:
            type: string
          shorttag:
            type: boolean
            default: true
        steps:
          - run:
              name: Build docker image for App development using << parameters.service >>
              command: docker-compose -f << parameters.file >> build --no-cache --pull << parameters.service >>
          - when:
              condition: << parameters.shorttag >>
              steps:
                - run:
                    environment:
                      OS6TAG: 6
                      OS7TAG: 7
                      OS8TAG: 8
                    command: docker-compose -f << parameters.file >> build << parameters.service >>
          - run:
              name: Login into Docker Hub
              command: docker login -u $DOCKER_USER -p $DOCKER_PASS
          - run:
              name: Push image into Docker Hub
              command: docker-compose -f << parameters.file >> push << parameters.service >>
          - when:
              condition: << parameters.shorttag >>
              steps:
                - run:
                    environment:
                      OS6TAG: 6
                      OS7TAG: 7
                      OS8TAG: 8
                    command: docker-compose -f << parameters.file >> push << parameters.service >>

    jobs:
      rpmbuild:
        parameters:
          base_file:
            type: string
            default: "docker-compose.base.yml"
          build_file:
            type: string
            default: "docker-compose.yml"
          base_service:
            type: string
          build_service:
            type: string
          bintray_uploader:
            type: string
        executor: centos
        steps:
          - submodules
          - base:
              file: << parameters.base_file >>
              service: << parameters.base_service >>
          - build:
              file: << parameters.build_file >>
              service: << parameters.build_service >>
          - rpm:
              file: << parameters.build_file >>
              service: << parameters.build_service >>
          - bintray:
              uploader: << parameters.bintray_uploader >>
      image:
        parameters:
          compose_file:
            type: string
            default: "build/docker-compose.yml"
          build_service:
            type: string
        executor: centos
        steps:
          - submodules
          - image:
              file: << parameters.compose_file >>
              service: << parameters.build_service >>

workflows:
  php7build:
    jobs:
      - docker-rpmbuild/rpmbuild:
          name: centos7php7
          base_service: centos7php7base
          build_service: centos7php7
          bintray_uploader: centos7bintray
      - docker-rpmbuild/rpmbuild:
          name: centos7php7rel
          base_service: centos7php7base
          build_service: centos7php7rel
          bintray_uploader: centos7bintray
      - docker-rpmbuild/rpmbuild:
          name: centos8php7
          base_service: centos8php7base
          build_file: docker-compose.el8.yml
          build_service: centos8php7
          bintray_uploader: centos8bintray
      - docker-rpmbuild/rpmbuild:
          name: centos8php7rel
          base_service: centos8php7base
          build_file: docker-compose.el8.yml
          build_service: centos8php7rel
          bintray_uploader: centos8bintray
      - docker-rpmbuild/image:
          name: centos7php7build
          build_service: centos7php7build
          requires:
            - centos7php7
      - docker-rpmbuild/image:
          name: centos7php7buildrel
          build_service: centos7php7buildrel
          requires:
            - centos7php7rel
      - docker-rpmbuild/image:
          name: centos8php7build
          compose_file: build/docker-compose.el8.yml
          build_service: centos8php7build
          requires:
            - centos8php7
      - docker-rpmbuild/image:
          name: centos8php7buildrel
          compose_file: build/docker-compose.el8.yml
          build_service: centos8php7buildrel
          requires:
            - centos8php7rel
      - docker-rpmbuild/image:
          name: centos7php7run
          compose_file: run/docker-compose.yml
          build_service: centos7php7run
          requires:
            - centos7php7
      - docker-rpmbuild/image:
          name: centos7php7devbase
          compose_file: run/docker-compose.yml
          build_service: centos7php7devbase
          requires:
            - centos7php7
      - docker-rpmbuild/image:
          name: centos8php7run
          compose_file: run/docker-compose.el8.yml
          build_service: centos8php7run
          requires:
            - centos8php7
      - docker-rpmbuild/image:
          name: centos8php7devbase
          compose_file: run/docker-compose.el8.yml
          build_service: centos8php7devbase
          requires:
            - centos8php7
      - docker-rpmbuild/image:
          name: centos7php7dev
          compose_file: run/docker-compose.dev.yml
          build_service: centos7php7dev
          requires:
            - centos7php7devbase
      - docker-rpmbuild/image:
          name: centos8php7dev
          compose_file: run/docker-compose.dev.yml
          build_service: centos8php7dev
          requires:
            - centos8php7devbase