version: 2.1

orbs:
  docker-rpmbuild: aursu/rpmbuild@1.0.0

workflows:
  php7build:
    jobs:
      - docker-rpmbuild/rpmbuild:
          name: centos7php7
          base_service: centos7php7base
          build_service: centos7php7
          bintray_uploader: centos7bintray
      - docker-rpmbuild/rpmbuild:
          name: centos7php7rel
          base_service: centos7php7base
          build_service: centos7php7rel
          bintray_uploader: centos7bintray
      - docker-rpmbuild/rpmbuild:
          name: centos8php7
          base_service: centos8php7base
          build_file: docker-compose.el8.yml
          build_service: centos8php7
          bintray_uploader: centos8bintray
      - docker-rpmbuild/rpmbuild:
          name: centos8php7rel
          base_service: centos8php7base
          build_file: docker-compose.el8.yml
          build_service: centos8php7rel
          bintray_uploader: centos8bintray
      - docker-rpmbuild/image:
          name: centos7php7build
          build_service: centos7php7build
          requires:
            - centos7php7
      - docker-rpmbuild/image:
          name: centos7php7buildrel
          build_service: centos7php7buildrel
          requires:
            - centos7php7rel
      - docker-rpmbuild/image:
          name: centos8php7build
          compose_file: build/docker-compose.el8.yml
          build_service: centos8php7build
          requires:
            - centos8php7
      - docker-rpmbuild/image:
          name: centos8php7buildrel
          compose_file: build/docker-compose.el8.yml
          build_service: centos8php7buildrel
          requires:
            - centos8php7rel
      - docker-rpmbuild/image:
          name: centos7php7run
          compose_file: run/docker-compose.yml
          build_service: centos7php7run
          requires:
            - centos7php7
      - docker-rpmbuild/image:
          name: centos7php7devbase
          compose_file: run/docker-compose.yml
          build_service: centos7php7devbase
          requires:
            - centos7php7
      - docker-rpmbuild/image:
          name: centos8php7run
          compose_file: run/docker-compose.el8.yml
          build_service: centos8php7run
          requires:
            - centos8php7
      - docker-rpmbuild/image:
          name: centos8php7devbase
          compose_file: run/docker-compose.el8.yml
          build_service: centos8php7devbase
          requires:
            - centos8php7
      - docker-rpmbuild/image:
          name: centos7php7dev
          compose_file: run/docker-compose.dev.yml
          build_service: centos7php7dev
          requires:
            - centos7php7devbase
      - docker-rpmbuild/image:
          name: centos8php7dev
          compose_file: run/docker-compose.dev.yml
          build_service: centos8php7dev
          requires:
            - centos8php7devbase