version: "3.5"
services:
  centos7php7run:
    build:
      context: .
      args:
        centos: $OS7
    image: "aursu/php7build:${OS7TAG}-runtime"
  centos7php7devbase:
    build:
      context: .
      args:
        image: nodedev
        centos: $OS7
    image: "aursu/php7build:${OS7TAG}-devbase"