version: "3.5"
services:
  centos7php7dev:
    build:
      context: dev
    image: aursu/php7build:7-dev
  centos8php7dev:
    build:
      context: dev
      args:
        image: 8-devbase
    image: aursu/php7build:8-dev