version: "3.5"
services:
  centos8php7run:
    build:
      context: .
      dockerfile: Dockerfile.el8
      args:
        centos: $OS8
    image: "aursu/php7build:${OS8TAG}-runtime"
  centos8php7devbase:
    build:
      context: .
      dockerfile: Dockerfile.el8
      args:
        image: nodedev
        centos: $OS8
    image: "aursu/php7build:${OS8TAG}-devbase"